contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
baseurl: "http://scristofari.github.io/"
title: "Sylvain Cristofari"
description: "Web developer"
canonifyurls: true
theme: "hyde"

params:
  description: "Web developer"