contentdir: "content"
layoutdir: "layouts"
publishdir: "public"

baseurl: "http://scristofari.github.io/"

title: "Sylvain Cristofari"
author: "Sylvain Cristofari"

description: "Web developer"
canonifyurls: true
theme: "hugo-uno"

taxonomies:
  category: "categories"
  tag: "tags"

params:
  AuthorName: "Sylvain"
  github: "scristofari"
  twitter: "cristofari_s"
  linkedin: "sylvain-cristofari-80838784"
  email: "s.cristofari@gmail.com"
  description: "Web developer / Gopher"
  logo: "https://avatars3.githubusercontent.com/u/3876389?v=3&s=460"

blackfriday:
   plainIDAnchors: true
   hrefTargetBlank: true

# git push origin `git subtree split --prefix=public hugo`:master --force
